# Numpy and Inbuilt Functions 

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6,6,7]
a=np.array(l)

In [3]:
a

array([1, 2, 3, 4, 5, 6, 6, 7])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(8,)

In [6]:
l1=[1,2,3,4,5]
l2=[2,3,4,5,5]
l3=[3,4,5,7,8]

a=np.array([l1,l2,l3])

In [7]:
a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 5],
       [3, 4, 5, 7, 8]])

In [8]:
a.shape

(3, 5)

In [9]:
a.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [5, 3, 4],
       [5, 7, 8]])

In [14]:
a.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 5],
       [3, 4, 5, 7, 8]])

In [15]:
a.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 5, 3, 4, 5, 7, 8]])

In [16]:
a.reshape(15,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [5],
       [5],
       [3],
       [4],
       [5],
       [7],
       [8]])

In [23]:
b=np.array([1,2,3,5,4,7,4,8])
b

array([1, 2, 3, 5, 4, 7, 4, 8])

In [24]:
b[2]

3

In [26]:
l1=[1,2,3,4,5]
l2=[2,3,4,5,5]
l3=[3,4,5,7,8]

a=np.array([l1,l2,l3])

In [27]:
a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 5],
       [3, 4, 5, 7, 8]])

In [30]:
a[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 5],
       [3, 4, 5, 7, 8]])

In [31]:
a[:,3:]

array([[4, 5],
       [5, 5],
       [7, 8]])

In [32]:
a[:,:3]

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [33]:
a[1:,:3]

array([[2, 3, 4],
       [3, 4, 5]])

In [34]:
a[:2,3:]

array([[4, 5],
       [5, 5]])

In [36]:
a[1:,1:3]

array([[3, 4],
       [4, 5]])

In [38]:
a[1:2,1:4]

array([[3, 4, 5]])

In [40]:
a[:,0:2]

array([[1, 2],
       [2, 3],
       [3, 4]])

In [42]:
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
l3=[9,7,6,8,9]

a=np.array([l1,l2,l3])

In [43]:
a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [45]:
a[1:,2:4]

array([[4, 5],
       [6, 8]])

In [46]:
a[1:2,1:4]

array([[3, 4, 5]])

In [47]:
r=np.arange(1,5)

In [48]:
r

array([1, 2, 3, 4])

In [49]:
r=np.arange(1,10,step=2)

In [50]:
r

array([1, 3, 5, 7, 9])

In [4]:
r=np.linspace(1,10,50)

In [5]:
r

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [6]:
a=np.array([1,2,3,4,5,5])
a

array([1, 2, 3, 4, 5, 5])

In [9]:
ar=a[3:]=100

In [10]:
ar=a

In [11]:
a

array([  1,   2,   3, 100, 100, 100])

In [15]:
ar=a.copy()

In [17]:
print(a)
ar[3:]=500
print(ar)

[  1   2   3 100 100 100]
[  1   2   3 500 500 500]


In [20]:
v=2
a%2

array([1, 0, 1, 0, 0, 0], dtype=int32)

In [21]:
a[a<3]

array([1, 2])

In [25]:
np.ones((5,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [26]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.random.rand(3,5)

array([[0.04343609, 0.54806488, 0.00211434, 0.94125608, 0.62600178],
       [0.98667577, 0.88887155, 0.84291789, 0.10953815, 0.93032414],
       [0.32494533, 0.69177021, 0.37804395, 0.48580842, 0.57096417]])

In [45]:
np.random.rand(5,2)

array([[0.36530041, 0.92895495],
       [0.45457045, 0.94966895],
       [0.12423428, 0.13789648],
       [0.94308144, 0.71224304],
       [0.47644263, 0.62062504]])